### ISSUE TITLE
Bug - Scanner fails in case of no rule tags filters

### ISSUE THREAD

**Issue by hoksanyip** [abnamro/repository-scanner#234]
**Describe the bug**

When you do not provide any tag filtering on the rules, the repository scanner is failing. This is probably due to the change [here](https://github.com/abnamro/resc-vcs-scanner/pull/37/files#diff-f83b58dfaafa1af8c313ab42a2dabf0348f952fb9cf31cc706b1268313c4adb2R93).

**To Reproduce**
1. Deploy the helm chart while leaving the following values empty: `resc-vcs-scanner-secrets.config.include_tags` and `resc-vcs-scanner-secrets.config.exclude_tags`.
2. Wait for or manually trigger the CronJob to scrape the repositories.
3. Check logs in `resc-vcs-scanner-secrets`

**Expected behavior**
In case no tags filtering is specified, then the code should work without applying any filtering. This would probably be solved by returning an empty set `{}` instead of `None` when nothing is specified (see this line: https://github.com/abnamro/resc-vcs-scanner/pull/37/files#diff-f83b58dfaafa1af8c313ab42a2dabf0348f952fb9cf31cc706b1268313c4adb2R93)

**Screenshots**

The `resc-vcs-scanner-secrets` pod returns the following error:

> `ERROR - celery.app.trace - YYYY-MM-DD HH:MM:SS,MS - Task scan_repository[00000000-0000-0000-0000-000000000000] raised unexpected: TypeError("'NoneType' object is not iterable")`
> `Traceback (most recent call last):`
> ` File "/home/apiuser/.local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task`
>`    R = retval = fun(*args, **kwargs)`
>`                 ^^^^^^^^^^^^^^^^^^^^`
>`  File "/home/apiuser/.local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__`
>`    return self.run(*args, **kwargs)`
>`           ^^^^^^^^^^^^^^^^^^^^^^^^^`
>`  File "/vcs_scanner/src/vcs_scanner/secret_scanners/celery_worker.py", line 93, in scan_repository`
>`    include_tags = list(set(include_tags) | set(vcs_instance.include_tags))`

**Environment information**
 - Operating System: [N/A]
 - Browser [N/A]
 - RESC Version [3.5.0]

**Deployment method**
 - [ ] Docker Compose
 - [X] Kubernetes

**Additional context**

**Comment by fatma-dahmane** [comment]
Thank you for reporting this.
Bug fixed  in resc-vcs-scaner version 3.6.1.
Closing the issue.
